version: '3.8'

services:
  web-downloader:
    build: .
    container_name: web-downloader
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
