version: "3.9"
services:
  yt-dlp-web:
    build:
      context: .
      dockerfile: Dockerfile  # Uses the Dockerfile in current directory
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000 (adjust as needed).
    volumes:
      - ./downloads:/app/downloads # Map a host directory to container downloads.
    restart: always # Automatically restart if the container crashes.